# Generated by Django 2.1.7 on 2019-04-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='area',
            new_name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
