# Generated by Django 2.1.7 on 2019-04-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0006_auto_20190408_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Old')], max_length=10),
        ),
    ]
